"""add opt in fields to user

Revision ID: 10419d21e3d0
Revises: 92f9a97e9001
Create Date: 2026-06-02 21:38:25.621650

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "10419d21e3d0"
down_revision: Union[str, None] = "92f9a97e9001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("share_my_data_to_sponsor", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "user", sa.Column("retain_my_data_for_next_pycon", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "retain_my_data_for_next_pycon")
    op.drop_column("user", "share_my_data_to_sponsor")
    # ### end Alembic commands ###
