"""create stream watch session table

Revision ID: 80a7628ad31b
Revises: 92f9a97e9001
Create Date: 2026-06-07 08:45:21.674891

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "80a7628ad31b"
down_revision: Union[str, None] = "92f9a97e9001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stream_watch_session",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("stream_id", sa.UUID(), nullable=False),
        sa.Column("schedule_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("watched_seconds", sa.Integer(), nullable=False),
        sa.Column("last_position_seconds", sa.Float(), nullable=False),
        sa.Column("qualified", sa.Boolean(), nullable=False),
        sa.Column("client_session_id", sa.String(length=255), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["public.schedule.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stream_id"],
            ["public.stream.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["public.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_stream_watch_session_client_session_id"),
        "stream_watch_session",
        ["client_session_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_stream_watch_session_id"),
        "stream_watch_session",
        ["id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_stream_watch_session_mode"),
        "stream_watch_session",
        ["mode"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_stream_watch_session_schedule_id"),
        "stream_watch_session",
        ["schedule_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_stream_watch_session_stream_id"),
        "stream_watch_session",
        ["stream_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_stream_watch_session_user_id"),
        "stream_watch_session",
        ["user_id"],
        unique=False,
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_public_stream_watch_session_user_id"),
        table_name="stream_watch_session",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_stream_watch_session_stream_id"),
        table_name="stream_watch_session",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_stream_watch_session_schedule_id"),
        table_name="stream_watch_session",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_stream_watch_session_mode"),
        table_name="stream_watch_session",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_stream_watch_session_id"),
        table_name="stream_watch_session",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_stream_watch_session_client_session_id"),
        table_name="stream_watch_session",
        schema="public",
    )
    op.drop_table("stream_watch_session", schema="public")
    # ### end Alembic commands ###
